# Does not work on anything but osx for some reason
os: osx
language: java
cache:
  directories:
  - build-tools
  - $HOME/.m2
before_install:
- mkdir -p build-tools
- curl https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -o build-tools/BuildTools.jar
- (cd build-tools && travis_retry java -jar BuildTools.jar --rev 1.9.2)
- (cd build-tools && travis_retry java -jar BuildTools.jar --rev 1.12)
- (cd build-tools && travis_retry java -jar BuildTools.jar --rev 1.12.1)
